version: '3'

services:
  nginx-web-1:
    image: codertravel/nginx-web:latest
    restart: always
  nginx-web-2:
    image: codertravel/nginx-web:latest
    restart: always

  haproxy-lb:
    image: codertravel/haproxy-lb:latest
    ports:
      - "80:80"
    restart: always
