version: '3'

services:
  nginx-web-1:
    image: codertravel/nginx-web:latest
    restart: always
  nginx-web-2:
    image: codertravel/nginx-web:latest
    restart: always

  haproxy-lb:
    build:
      context: ./haproxy-lb
      dockerfile: Dockerfile
    image: haproxy-lb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${PWD}/selfsigned.pem:/usr/local/etc/ssl/certs/selfsigned.pem"
    restart: always
