name: '[CI] Web'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - edited
    paths:
      - nginx/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
